# Generated by Django 6.0 on 2025-12-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('standard', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('school_house', models.CharField(choices=[('Red', 'Red House'), ('Yellow', 'Yellow House'), ('Blue', 'Blue House'), ('Green', 'Green House')], max_length=255)),
                ('admission_date', models.DateField()),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
