# Generated by Django 6.0 on 2025-12-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('designation', models.CharField(choices=[('HR', 'HR'), ('pdev', 'Python Developer'), ('jdev', 'Java Developer'), ('cdev', 'C++ Developer'), ('Software Engineer', 'Software Engineer'), ('QA Engineer', 'QA Engineer'), ('Project Manager', 'Project Manager')], max_length=255)),
                ('joining_date', models.DateField()),
                ('dob', models.DateField()),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
